sudo: required

# Install Docker
services:
  - docker

# Execute logic
script:
  - echo "Hello Students!"

after_success:
  # Build all the docker files
  - docker build -t pavanleton/zomato-shapeai-client ./client
  - docker build -t pavanleton/zomato-shapeai-server ./server
  - docker build -t pavanleton/zomato-shapeai-nginx ./nginx

  # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push pavanleton/zomato-shapeai-client
  - docker push pavanleton/zomato-shapeai-server
  - docker push pavanleton/zomato-shapeai-nginx

deploy:
  # deploy to AWS EBS
  provider: elasticbeanstalk
  region: ap-south-1
  app: Zomato-clone-shapeai
  env: Zomatocloneshapeai-env
  bucket_name: elasticbeanstalk-ap-south-1-701994403871
  bucket_path: zomatoshapeai
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
